# Generated by Django 5.2.5 on 2025-10-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_created_at_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], default='BUYER', max_length=10),
        ),
    ]
