# Generated by Django 5.2.5 on 2025-12-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional. Enter a valid email address.', max_length=254),
        ),
    ]
