# Generated by Django 5.2.5 on 2025-10-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='stores_stor_name_988b60_idx'), models.Index(fields=['city'], name='stores_stor_city_613ee7_idx'), models.Index(fields=['is_active'], name='stores_stor_is_acti_12939d_idx')],
            },
        ),
    ]
