# Generated by Django 5.2.5 on 2025-10-23 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_updated_at_alter_store_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(default='Indonesia', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='store_hours',
            field=models.TextField(blank=True, help_text='Store opening hours (formatted text or JSON)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['country'], name='stores_stor_country_88a141_idx'),
        ),
    ]
